import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '../context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });
//New Font fromm Google Fonts (Use in the html return -> <body className={poppins.className}>)
const poppins = Poppins({ weight: "400", subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ThemeProvider>
          
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        
        </ThemeProvider>
      </body>
    </html>
  )
}
